(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; パッケージリポジトリの指定
(source gnu)
(source melpa)
(source marmalade)

;; インストールしたいパッケージを記述
(depends-on "anzu")
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "tern")
(depends-on "company")
(depends-on "company-tern")
(depends-on "js2-mode")
(depends-on "json-mode")

;; バージョン指定も可能
(depends-on "magit" "0.8.1")
;; 直接リポジトリの場所を指定可能
;; (depends-on "magit" :git "https://github.com/magit/magit.git")

